### ISSUE TITLE
Return on Top link on right

### ISSUE THREAD

**Issue by OpenCode** [nerdzeu/nerdz-template-metro#4]
Please, move the Return on Top link (the up arrow) on the right side because, now, the icon stay on some important links

**Comment by DrJest** [comment]
Screen please. That's strange, it's designed to appear after the left bar is left above

**Comment by OpenCode** [comment]
![scrot](https://f.cloud.github.com/assets/265697/1918581/588e5d42-7dc1-11e3-8f70-b04ad7575db2.png)

**Comment by DrJest** [comment]
oh didnt considered friends xD

**Comment by DrJest** [comment]
ok moved it downward, should not interfer with friendlist

**Comment by OpenCode** [comment]
Thanks maddafakka!!!! XD
