### ISSUE TITLE
la licenza non va bene :(

### ISSUE THREAD

**Issue by mcilloni** [nerdzeu/nerdz-template-metro#5]
Non puoi rilasciare il templare sotto MIT zio, violi la AGPL di nerdz così :(
Ninnoli eh, ma se è così...

**Comment by DrJest** [comment]
Si ho capito, appena scrivo un nuovo script per la textarea la cambio, e
carico i sorgenti Jade, Less e coffee
Il 12/apr/2014 10:16 "mcilloni" notifications@github.com ha scritto:

**Comment by nerdzeu** [comment]
Allora togli anche dal gitignore (sia del modulo che di nerdz) i .jade, .less :>

**Comment by DrJest** [comment]
Si scialli ragazzi, giuro che non vi farò causa se voi non la farete a me
Il 12/apr/2014 10:33 "Paolo Galeone" notifications@github.com ha scritto:

**Comment by DrJest** [comment]
Quel gitignore l'ho messo perché ero stufo di avere una pagina di untracked
ogni volta che facevo un git status.
Il 12/apr/2014 10:34 "Simone Albano" dc.jest@gmail.com ha scritto:

**Comment by mcilloni** [comment]
sai che ti lovviamo tantissimo e che siamo riconoscenti del fatto che senza te staremmo ancora usando la versione desktop sul cellulare <3
